version: '3'

volumes:
  local_postgres_data: {}

services:
  django:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    volumes:
      - ./simple_project:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=test_db
      - POSTGRES_USER=debug
      - POSTGRES_PASSWORD=debug
    command: /start

  postgres:
    image: postgres:11
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=test_db
      - POSTGRES_USER=debug
      - POSTGRES_PASSWORD=debug
